export const ADD_ARTICLE = "ADD_ARTICLE";

export const ADD_PRIMARY_COLOR_REQUEST = "ADD_PRIMARY_COLOR_REQUEST";
export const REMOVE_PRIMARY_COLOR_REQUEST = "REMOVE_PRIMARY_COLOR_REQUEST";
export const ADD_SECONDARY_COLOR_REQUEST = "ADD_SECONDARY_COLOR_REQUEST";
export const REMOVE_SECONDARY_COLOR_REQUEST = "REMOVE_SECONDARY_COLOR_REQUEST";
export const COLOR_CONTRAST_ANALYZE_REQUEST = "COLOR_CONTRAST_ANALYZE_REQUEST";
export const COLOR_CONTRAST_SUGGESTION_REQUEST = "COLOR_CONTRAST_SUGGESTION_REQUEST";
export const SELECTED_WCAG_LEVELS_AA = "SELECTED_WCAG_LEVELS_AA";
export const SELECTED_WCAG_LEVELS_AAA = "SELECTED_WCAG_LEVELS_AAA";
export const APPLY_COLOR_CONTRAST_SUGGESTION = "APPLY_COLOR_CONTRAST_SUGGESTION";